version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: automail_db
      POSTGRES_USER: francoveron
      POSTGRES_PASSWORD: qhkqd5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
